### ISSUE TITLE
AMP Review #1

### ISSUE THREAD

**Issue by melaniebeck** [fastforwardlabs/continuous-monitoring#1]
Fabulous AMP, @andrewrreed! It's polished and well-documented, and the code is tight, clean, and clear. I also love the overall structure of the repo, e.g., removing the `cml` directory in favor of a combined `scripts` directory. I think it really streamlines the codebase.  I'll be using this repo as my go-to example from here on out. 

## High-level thoughts
As a user of this AMP, what should I be paying attention to once the project setup is complete? Once everything is set up, I feel kind of lost.  
   * Should we be exploring the Evidently dashboard? If so, what should we be looking for/at? How do you switch between the dashboards? (Nevermind, I think you've combined the three drift dashboards into one? But that wasn't obvious at first.) How can I tell that this has been a simulation over several months? 
   * Should I be looking at the code instead? What piece of the code? Probably the Simulation, I would guess. 
   * The more I look at the code (which is *awesome* btw), I'm realizing that multiple Evidently dashboards are being generated throughout the Simulation process? So, in theory, if someone were running the AMP setup and knew to open the Evidently dashboard _while_ step 7 was running, they would see that dashboard update? It might be instructive to provide the steps to rerun the Simulation in order to visualize these dashboards as they're updated in order to get a feel for how the simulation is progressing. 

Perhaps we could add a bit more instruction/information in the Readme to guide users towards the most important parts (either the code or the dashboard, or both) of this AMP, as a call to action. 

## Failure on legacy engines
First off, are we supposed to be testing on legacy engines? I think the automated testing would probably cover this but I wasn't sure so I used the _Recommended_ legacy engine (15-cml-2021.09-2), with `DEV_MODE = True` and got a really big error when running step 7 (Simulation): 

<img width="1386" alt="Screen Shot 2022-01-13 at 11 01 34 AM" src="https://user-images.githubusercontent.com/7946684/149376048-9fc8c7d8-6a63-46f4-9f01-de46dd82ef10.png">

<img width="1359" alt="Screen Shot 2022-01-13 at 11 01 47 AM" src="https://user-images.githubusercontent.com/7946684/149376647-bb256317-cffb-4992-bd1d-eff5b2a5b989.png">

<img width="1356" alt="Screen Shot 2022-01-13 at 11 01 57 AM" src="https://user-images.githubusercontent.com/7946684/149376905-f30c04f4-b8fb-4e0e-b4b7-d2a63e99050a.png">

It looks like more kernels need to specified but I'm not sure where. 

## Minor points

- [x] Should there be a mention of which Python version this was developed against? I know the defaults are stored in the .yaml file but during project setup, the Configure Project screen allows the user to choose their own resources. I'm pretty sure the selections displayed are defaults populated by the .yaml (so Runtimes was highlighted, with Python 3.6 selected) but I second-guessed those choices and went to verify in the Readme and realized I would need to check the .yaml instead. 
- [x] Speaking of second-guessing those populated values -- the .yaml indicates that the default value for the DEV_MODE environment variable should be "False" but this is populated as "false" which fails when you hit Launch Project (see below). I had to manually update to "False" to proceed. Should this be a Jira? 

![Screen Shot 2022-01-12 at 2 14 25 PM](https://user-images.githubusercontent.com/7946684/149214875-a32880b6-fc23-40e5-a189-b016166783db.png)

- [x] The AMP setup process takes a long time when using the full dataset (20 minutes alone to run the simulation step) -- should we include a note about how long it takes?

**Comment by andrewrreed** [comment]
Thanks for the review @melaniebeck! I've made the following edits to address this excellent feedback:

- Added more details and "calls to action" for what users should attend to upon completion of the simulation task. I completely agree that without more context users are left confused. (Note - I did not add a separate README like we had discussed in our 1:1. I started to do so, but it was very repetitive to the original one... so I decided just to expand the main README a bit. Please let me know if you think it could still use more clarification!)
- Added the `kernel` param to the cmlapi.CreateApplicationRequest() so it works on Engines + manually tested
- Added a mention of which Python version it was developed against in the README
- Added a callout in the README to alert users that project setup can take a while....
- Added a thumbnail image to the Review doc
- Added `tqdm` progress bar to simulation

As a final FYI - heres [the Jira](https://jira.cloudera.com/browse/DSE-19177) for the bug you pointed out. I filed it some time back, but it has yet to get picked up and assigned.

Let me know if you have any other comments/suggestions/feedback. Thanks again!

**Comment by melaniebeck** [comment]
I love the additional direction/description in the Readme! I feel like I know what I could/should be looking at and how to find it now. I think this absolutely satisfies the "call to action." I also appreciate the added detail/discussion re the Evidently dashboard. Much clearer! 

The `tqdm` on the simulation was really nice, btw. Way to go above and beyond! 

I'm calling this review officially "completed."
