### ISSUE TITLE
Step 7 fails

### ISSUE THREAD

**Issue by ValdezBalderas** [fastforwardlabs/continuous-monitoring#3]
Step 7 fails. 

<img width="733" alt="Screen Shot 2022-01-21 at 11 53 07 AM" src="https://user-images.githubusercontent.com/28984461/150583894-fb530553-cd22-41ae-a215-0aa8ecd41041.png">

These are the details:

<img width="1152" alt="Screen Shot 2022-01-21 at 11 50 13 AM" src="https://user-images.githubusercontent.com/28984461/150583538-c2daba3c-e4af-4035-bb09-acbcff222c15.png">

Though steps 1-6 look as completed, I looked at their details and saw that Step 1 has this:

<img width="1000" alt="Screen Shot 2022-01-21 at 12 05 45 PM" src="https://user-images.githubusercontent.com/28984461/150585509-7b2c5e37-3598-46ec-b74d-d1b2aadbb3d0.png">

**Comment by ValdezBalderas** [comment]
The 7 steps complete successfully when run on cml-eng. 
@andrewrreed has mentioned that the source of the problem on fflab-4 (where the issue was observed) was due to to that cluster not having the "model metrics" feature enabled.

The only remaining question for me is the error message that can be seen under details of step 1, which persists on cml-eng cluster, in spite of all steps completing successfully.

**Comment by andrewrreed** [comment]
Thanks @ValdezBalderas.

I just pushed a fix for the install error here: https://github.com/fastforwardlabs/continuous-monitoring/commit/c2978d599df3633c8937ba621e5f0128a9e0a5cf

It looks like that `!pip install` thats inside the try/except block was executing regardless of if the ModuleNotFoundError hits or not. I've updated logic to avoid this and manually tested the change
