### ISSUE TITLE
Possibly an FFLAB-4 Issue, not an AMP issue

### ISSUE THREAD

**Issue by ValdezBalderas** [fastforwardlabs/continuous-monitoring#4]
- This seems to be an issue with fflab-4 rather than with the AMP, but I will leave this here for the record. This issue is not present on eng-cml-cluster. On cfflab-4, I tried

<img width="890" alt="Screen Shot 2022-01-21 at 9 12 41 AM" src="https://user-images.githubusercontent.com/28984461/150561172-3d02da32-5832-4064-b954-80aeaea88593.png">

but this gave me the error (same error was triggered using the https instead of ssh address). 

<img width="781" alt="Screen Shot 2022-01-21 at 9 15 02 AM" src="https://user-images.githubusercontent.com/28984461/150561543-4bd7a7ef-40f6-4e30-ba60-c911c37a7e15.png">

**Comment by andrewrreed** [comment]
Thanks for reporting - this is due to the fact that we don't have the `model_metrics` feature enabled on our FFLab-4 cluster

![image](https://user-images.githubusercontent.com/23462538/150854843-0770ba03-5643-4fa1-a0d0-e67f86468929.png)
