### ISSUE TITLE
Project configuration 'false' 

### ISSUE THREAD

**Issue by ValdezBalderas** [fastforwardlabs/continuous-monitoring#6]
I think this was spotted before, but I was't sure about the outcome. I its fixed manually by changing 'false' to 'False'
<img width="865" alt="Screen Shot 2022-01-24 at 2 36 23 PM" src="https://user-images.githubusercontent.com/28984461/150868903-7c975622-0a59-42f4-8a63-173d44943f7c.png">

**Comment by andrewrreed** [comment]
Yep, this is a known issue and [documented here](https://jira.cloudera.com/browse/DSE-19177?filter=40034). Thanks!
